[package]
name = "telegrand"
version = "0.1.0"
authors = ["Marco Melorio <marco.melorio@protonmail.com>"]
edition = "2021"

[dependencies]
adw = { version = "0.1", package = "libadwaita" }
anyhow = "1.0"
futures = { version = "0.3", default-features = false }
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk = { version = "0.4", package = "gtk4" }
indexmap = "1.7"
locale_config = "0.3"
log = "0.4"
once_cell = "1.9"
pretty_env_logger = "0.4"
qrcode-generator = { version = "4.1", default-features = false }
regex = "1.5"
tdgrand = { git = "https://github.com/melix99/tdgrand", branch = "api-improvements", default-features = false }
tokio = { version = "1", features = ["rt-multi-thread"] }
tokio-stream = { version = "0.1", features = ["fs"] }
webp = "0.2"
